shelf_x: 2.25
shelf_y: 2.25
shelf_z: 0.75

shelf_box_x: 1.0
shelf_box_y: 1.0
shelf_box_z: 1.5

goal_pose_x:     1.0
goal_pose_y:     0.3
goal_pose_z:     0.25
goal_pose_roll:  90
goal_pose_pitch: -45
goal_pose_yaw:   180

start_pose_x:     1.0
start_pose_y:     0.3
start_pose_z:     0.25
start_pose_roll:  90
start_pose_pitch: -45
start_pose_yaw:   180

#see gundam_moveit_config/config/ompl_planning.yaml for possible OMPL planners
# SBPL planners coming soon
narms_planner_id: "RRTkConfigDefault"
narms_planning_time: 10 # seconds

