manipulator_group_name: right_arm
max_grasp_candidates: 4

stow_positions:
#    - name: "one"
#      joint_vector_degs:
#        arm_1_shoulder_twist: 92.00
#        arm_2_shoulder_lift: 84.00
#        arm_3_elbow_twist: -102.00
#        arm_4_elbow_lift: 59.00
#        arm_5_wrist_twist: -13.0
#        arm_6_wrist_lift: 1.00
#        arm_7_gripper_lift: 24.00
#    - name: "two"
#      joint_vector_degs:
#        arm_1_shoulder_twist: -73.00
#        arm_2_shoulder_lift: -43.00
#        arm_3_elbow_twist: 11.00
#        arm_4_elbow_lift: 40.00
#        arm_5_wrist_twist: -85.00
#        arm_6_wrist_lift: 2.00
#        arm_7_gripper_lift: 25.00
    - name: "one"
      joint_vector_degs:
        limb_right_joint1: -61.58
        limb_right_joint2: 54.91
        limb_right_joint3: 7.82
        limb_right_joint4: 93.64
        limb_right_joint5: -51.47
        limb_right_joint6: 20.10
        limb_right_joint7: -10.96

# whether to extrude the current costmap and use as the octomap for queries to
# the arm executor
use_extrusion_octomap: false

# circumscribed radius of the gascan to filter out of the costmap and to use
# for detection of the gascan
object_filter_radius_m: 0.3

# the confidence (between 0 and 1) at which and above to consider the gascan
# picked up
gas_can_detection_threshold: 0.8

skip_viservo: true
