# collision object format:
# id: string
# type: string; "box", "sphere", "cylinder", "cone"
# pose:
#   position:
#     x: double
#     y: double
#     z: double
#   orientation:
#     r: double
#     p: double
#     y: double

collision_objects:
  - id: cube_1
    type: box # box | sphere | cylinder | cone
    pose:
      position: { x: 0.0, y: 0.0, z: 0.0 }
      orientation: { r: 0.0, p: 0.0, y: 0.0 }
    dims: { length: 1.0, width: 1.0, height: 1.0  }
  - id: cube_2
    type: box
    pose:
      position: { x: 0.0, y: 0.0, z: 0.0 }
      orientation: { r: 0.0, p: 0.0, y: 0.0 }
    dims: { length: 1.0, width: 1.0, height: 1.0  }
  - id: sphere_1
    type: sphere
    pose:
      position: { x: 0.0, y: 0.0, z: 0.0 }
      orientation: { r: 0.0, p: 0.0, y: 0.0 }
    dims: { radius: 1.0 }
  - id: cylinder_1
    type: cylinder
    pose:
      position: { x: 0.0, y: 0.0, z: 0.0 }
      orientation: { r: 0.0, p: 0.0, y: 0.0 }
    dims: { height: 1.0, radius: 1.0 }